// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetApp.Models;

#nullable disable

namespace VetApp.Migrations
{
    [DbContext(typeof(VetAppContext))]
    [Migration("20240705041502_resimdenemev2")]
    partial class resimdenemev2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Randevu", b =>
                {
                    b.Property<int>("RandevuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RandevuID"));

                    b.Property<int>("HayvanID")
                        .HasColumnType("int");

                    b.Property<int>("MusteriID")
                        .HasColumnType("int");

                    b.Property<string>("Notlar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RandevuTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("RandevuID");

                    b.HasIndex("HayvanID");

                    b.HasIndex("MusteriID");

                    b.ToTable("Randevular", (string)null);
                });

            modelBuilder.Entity("VetApp.Model.Asi", b =>
                {
                    b.Property<int>("AsiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsiID"));

                    b.Property<string>("AsiAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HayvanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("AsiID");

                    b.HasIndex("HayvanID");

                    b.ToTable("Asilar", (string)null);
                });

            modelBuilder.Entity("VetApp.Model.Musteri", b =>
                {
                    b.Property<int>("MusteriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCKimlik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriID");

                    b.ToTable("Musteriler", (string)null);
                });

            modelBuilder.Entity("VetApp.Model.TibbiKayit", b =>
                {
                    b.Property<int>("TibbiKayitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TibbiKayitID"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HayvanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("TibbiKayitID");

                    b.HasIndex("HayvanID");

                    b.ToTable("TibbiKayitlar", (string)null);
                });

            modelBuilder.Entity("VetApp.Models.Hayvan", b =>
                {
                    b.Property<int>("HayvanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HayvanID"));

                    b.Property<string>("Cins")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("HayvanAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MusteriID")
                        .HasColumnType("int");

                    b.Property<string>("ResimYolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HayvanID");

                    b.HasIndex("MusteriID");

                    b.ToTable("Hayvanlar", (string)null);
                });

            modelBuilder.Entity("VetApp.Models.Veteriner", b =>
                {
                    b.Property<int>("VeterinerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeterinerID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCKimlik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VeterinerID");

                    b.ToTable("Veterinerler", (string)null);
                });

            modelBuilder.Entity("Randevu", b =>
                {
                    b.HasOne("VetApp.Models.Hayvan", "Hayvan")
                        .WithMany("Randevular")
                        .HasForeignKey("HayvanID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VetApp.Model.Musteri", "Musteri")
                        .WithMany("Randevular")
                        .HasForeignKey("MusteriID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Hayvan");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("VetApp.Model.Asi", b =>
                {
                    b.HasOne("VetApp.Models.Hayvan", "Hayvan")
                        .WithMany("Asilar")
                        .HasForeignKey("HayvanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hayvan");
                });

            modelBuilder.Entity("VetApp.Model.TibbiKayit", b =>
                {
                    b.HasOne("VetApp.Models.Hayvan", "Hayvan")
                        .WithMany("TibbiKayitlar")
                        .HasForeignKey("HayvanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hayvan");
                });

            modelBuilder.Entity("VetApp.Models.Hayvan", b =>
                {
                    b.HasOne("VetApp.Model.Musteri", "Musteri")
                        .WithMany("Hayvanlar")
                        .HasForeignKey("MusteriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("VetApp.Model.Musteri", b =>
                {
                    b.Navigation("Hayvanlar");

                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("VetApp.Models.Hayvan", b =>
                {
                    b.Navigation("Asilar");

                    b.Navigation("Randevular");

                    b.Navigation("TibbiKayitlar");
                });
#pragma warning restore 612, 618
        }
    }
}
